[global]
port = 1701
auth file = /etc/ppp/chap-secrets
access control = no

[lns default]
exclusive = no
ip range = 10.0.1.10-10.0.1.100
local ip = 10.0.1.1
length bit = yes
require chap = yes
refuse pap = yes
require authentication = yes
name = l2tpd
ppp debug = yes
pppoptfile = /etc/ppp/options.xl2tpd
